name: ai_lab_minimalist
description: 极简版AI实验室：集成了风格迁移、换脸、AI扩图、物体移除等智能修图功能、个人中心、作品画廊及热门提示词社区。
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.0
  path: ^1.9.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
